---
- name: Deploy web server
  hosts: web
  become: true
  roles:
    - webserver # This line includes your new webserver role

- name: Install MariaDB server on db server
  hosts: db
  become: yes
  tasks:
    - name: Update package cache for MariaDB installation
      yum:
        name: '*'
        state: latest
        update_cache: yes # Ensure cache is updated before searching for MariaDB

    - name: Install MariaDB server package
      yum:
        # Amazon Linux 2023 typically uses 'mariadb105-server' or 'mariadb-server'
        # 'mariadb105-server' is common for newer AL versions.
        # If this fails, try 'mariadb-server'
        name: mariadb105-server
        state: present

    - name: Ensure MariaDB service is started and enabled
      service:
        name: mariadb # The service name for MariaDB is usually 'mariadb'
        state: started
        enabled: true
