---
# defaults/main.yml for webserver role

webserver_package_name: httpd
webserver_service_name: httpd
webserver_document_root: /var/www/html
webserver_server_name: your_web_server.example.com # Replace with your desired server name
